/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.c
**     Project     : TWR-K60D100M
**     Processor   : MK60DN512VMD10
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     All Rights Reserved.
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.4
** @brief
**
*/
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/

/* MODULE pin_mux. */

#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_mux.h"

//void configure_gpio_pins(uint32_t instance)
//{
//  switch(instance) {
//    case PORTA_IDX:                      /* PTA */
//      /* Affects PORTA_PCR19 register */
//      PORT_HAL_SetPassiveFilterCmd(PORTA,19u,false);
//      PORT_HAL_SetMuxMode(PORTA,19u,kPortMuxAsGpio);
//      PORT_HAL_SetPullMode(PORTA,19u,kPortPullUp);
//      PORT_HAL_SetPullCmd(PORTA,19u,true);
//      /* Affects PORTA_PCR10 register */
//      PORT_HAL_SetDriveStrengthMode(PORTA,10u,kPortLowDriveStrength);
//      PORT_HAL_SetMuxMode(PORTA,10u,kPortMuxAsGpio);
//      PORT_HAL_SetSlewRateMode(PORTA,10u,kPortSlowSlewRate);
//      /* Affects PORTA_PCR11 register */
//      PORT_HAL_SetDriveStrengthMode(PORTA,11u,kPortLowDriveStrength);
//      PORT_HAL_SetMuxMode(PORTA,11u,kPortMuxAsGpio);
//      PORT_HAL_SetSlewRateMode(PORTA,11u,kPortSlowSlewRate);
//      /* Affects PORTA_PCR28 register */
//      PORT_HAL_SetDriveStrengthMode(PORTA,28u,kPortLowDriveStrength);
//      PORT_HAL_SetMuxMode(PORTA,28u,kPortMuxAsGpio);
//      PORT_HAL_SetSlewRateMode(PORTA,28u,kPortSlowSlewRate);
//      /* Affects PORTA_PCR29 register */
//      PORT_HAL_SetDriveStrengthMode(PORTA,29u,kPortLowDriveStrength);
//      PORT_HAL_SetMuxMode(PORTA,29u,kPortMuxAsGpio);
//      PORT_HAL_SetSlewRateMode(PORTA,29u,kPortSlowSlewRate);
//      /* Affects PORTA_PCR26 register */
//      PORT_HAL_SetMuxMode(PORTA,26u,kPortMuxAsGpio);
//      break;
//    case PORTD_IDX:                      /* PTD */
//      PORT_HAL_SetPassiveFilterCmd(PORTD, 10u, false);
//      PORT_HAL_SetMuxMode(PORTD, 10u, kPortMuxAsGpio);
//      break;
//    case PORTE_IDX:                      /* PTE */
//      /* Affects PORTE_PCR26 register */
//      PORT_HAL_SetPassiveFilterCmd(PORTE,26u,false);
//      PORT_HAL_SetMuxMode(PORTE,26u,kPortMuxAsGpio);
//      PORT_HAL_SetPullMode(PORTE,26u,kPortPullUp);
//      PORT_HAL_SetPullCmd(PORTE,26u,true);
//      /* Affects PORTE_PCR28 register */
//      PORT_HAL_SetMuxMode(PORTE,28u,kPortMuxAsGpio);
//      break;
//    default:
//      break;
//  }
//}
void configure_adc_pins(uint32_t instance)
{
	switch(instance){
	case ADC0_IDX:
		PORT_HAL_SetMuxMode(PORTB,0u,kPortPinDisabled);
		PORT_HAL_SetMuxMode(PORTB,1u,kPortPinDisabled);
		PORT_HAL_SetMuxMode(PORTB,2u,kPortPinDisabled);
		PORT_HAL_SetMuxMode(PORTB,3u,kPortPinDisabled);

		PORT_HAL_SetMuxMode(PORTE,24u,kPortPinDisabled);
		PORT_HAL_SetMuxMode(PORTE,25u,kPortPinDisabled);
		break;
	case ADC1_IDX:
		PORT_HAL_SetMuxMode(PORTB,2u,kPortPinDisabled);
		PORT_HAL_SetMuxMode(PORTB,2u,kPortPinDisabled);
		break;
	}
}
void configure_i2c_pins(uint32_t instance)
{
  switch(instance) {
    case I2C1_IDX:                       /* I2C1 */
      /* Affects PORTC_PCR10 register */
      PORT_HAL_SetMuxMode(PORTC,10u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTC,10u,true);
      /* Affects PORTC_PCR11 register */
      PORT_HAL_SetMuxMode(PORTC,11u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTC,11u,true);
      break;
    default:
      break;
  }
}

void configure_rtc_pins(uint32_t instance)
{
  /* Affects PORTE_PCR26 register */
  PORT_HAL_SetMuxMode(PORTE,26u,kPortMuxAlt6);
}

void configure_uart_pins(uint32_t instance)
{
  switch(instance) {
  	case UART0_IDX:                        /* UART0 */
      /* Affects PORTE_PCR9 register */
      PORT_HAL_SetMuxMode(PORTB,16u,kPortMuxAlt3);
      /* Affects PORTE_PCR8 register */
      PORT_HAL_SetMuxMode(PORTB,17u,kPortMuxAlt3);
      break;
  	case UART2_IDX:
  	  PORT_HAL_SetMuxMode(PORTD,2u,kPortMuxAlt3);
	  PORT_HAL_SetMuxMode(PORTD,3u,kPortMuxAlt3);
	  break;
	case UART3_IDX:                        /* UART3 */
      /* Affects PORTC_PCR16 register */
      PORT_HAL_SetMuxMode(PORTB,10u,kPortMuxAlt3);
      /* Affects PORTC_PCR17 register */
      PORT_HAL_SetMuxMode(PORTB,11u,kPortMuxAlt3);
      break;

    default:
      break;
  }
}

/* Setup FTM pins to drive LED */
void configure_ftm_pins(uint32_t instance)
{
  switch(instance) {
  	case FTM0_IDX:						/* PWM µ÷ÖÆ*/
  	  PORT_HAL_SetMuxMode(PORTD,4u,kPortMuxAlt4);
  	  PORT_HAL_SetMuxMode(PORTD,5u,kPortMuxAlt4);
  	  PORT_HAL_SetMuxMode(PORTD,6u,kPortMuxAlt4);
  	  PORT_HAL_SetMuxMode(PORTD,7u,kPortMuxAlt4);
  	  break;
  	case FTM1_IDX:
      PORT_HAL_SetMuxMode(PORTA,12u,kPortMuxAlt7);
      PORT_HAL_SetMuxMode(PORTA,13u,kPortMuxAlt7);
      break;
  	case FTM2_IDX:
  	  PORT_HAL_SetMuxMode(PORTB,18u,kPortMuxAlt7);
  	  PORT_HAL_SetMuxMode(PORTB,19u,kPortMuxAlt7);
  	  break;
//    case FTM2_IDX:                       /* FTM2 */
//      /* Affects PORTA_PCR11 register (D7 - RED)*/
//      PORT_HAL_SetDriveStrengthMode(PORTA,11u,kPortLowDriveStrength);
//      PORT_HAL_SetMuxMode(PORTA,11u,kPortMuxAlt3);
//      PORT_HAL_SetSlewRateMode(PORTA,11u,kPortSlowSlewRate);
//      break;

    default:
      break;
  }
}


/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
